# plot growth rate
# x is a list containing tree vectors of equal site:
#    files: the path for the files generated by sfreemap.test.perf
#    types: the column name to be considered in the corresponding file
#    legend: the value to be added as a legend
plot_comparison <- function(x, xlabel, limit=NULL, output=NULL) {

    files <- x$files
    types <- x$types
    legend <- x$legend
    mode <- x$mode
    nsim <- x$nsim
    if (is.null(mode)) {
        mode <- rep('serial', length(files))
    }
    if (is.null(nsim)) {
        nsim <- rep(1, length(files))
    }

    if (!all.equal(length(files), length(types), length(legend))) {
        stop ("files, types and legend must have the same length")
    }

    data <- parse(files[1], types[1], legend[1], limit, mode[1], nsim[1], FALSE)
    first <- data
    speed_up <- list()
    for (i in 2:length(files)) {
        tmp <- parse(files[i], types[i], legend[i], limit, mode[i], nsim[i], FALSE)
        data <- rbind(data, tmp)
        speed_up[[legend[i]]] <- summary_speed_up(tmp$time, first$time)
    }

    if (!is.null(output)) {
        png(output, width=1024, height=768)
    }

    #breaks <- seq(0, max(data$value), 10)

    p <- ggplot(data, aes(x=value, y=time, group=legend, colour=factor(legend))) +
            stat_smooth(method='loess', fullrange=TRUE, se=FALSE) +
            geom_point() +
            theme_bw(base_size=26) +
            #scale_x_discrete(breaks=breaks) +
            scale_colour_brewer(palette="Set1", name = "") +
            theme(legend.position="top", axis.text.y=element_text(hjust=1.3)) +
            xlab(xlabel) +
            ylab("Tempo decorrido (segundos)")
    print(p)

    if (!is.null(output)) {
        dev.off()
    }

    return(list(data=data, speed_up=speed_up))
}

# plot growth rate
# x is a list containing tree vectors of equal site:
#    files: the path for the files generated by sfreemap.test.perf
#    types: the column name to be considered in the corresponding file
#    legend: the value to be added as a legend
plot_growth_rate <- function(x, limit=NULL, output=NULL) {

    files <- x$files
    types <- x$types
    legend <- x$legend

    if (!all.equal(length(files), length(types), length(legend))) {
        stop ("files, types and legend must have the same length")
    }


    data <- parse(files[1], types[1], legend[1], limit=limit, diff=TRUE)
    for (i in 2:length(files)) {
        tmp <- parse(files[i], types[i], legend[i], limit=limit, diff=TRUE)
        data <- rbind(data, tmp)
    }

    if (!is.null(output)) {
        png(output, width=1024, height=768)
    }

    p <- ggplot(data, aes(x=value, y=time, group=legend, colour=factor(legend))) +
            stat_smooth(method='loess', fullrange=TRUE, se=FALSE) +
            geom_point() +
            theme_bw(base_size=26) +
            scale_colour_brewer(palette="Set1", name = "") +
            theme(legend.position="top", axis.text.y=element_text(hjust=1.3)) +
            xlab("") +
            ylab("Diferença em execuções sucessivas (segundos)")
    print(p)

    if (!is.null(output)) {
        dev.off()
    }

    return(data)
}

# plot a boxplot
# this function is used by sfreemap.test.boxplot
plot_boxplot <- function(out_dir, out_file, data, y, xlabel, ylabel, line_data) {

    data <- data.frame(data)

	output <- paste(out_dir, out_file, sep='/')

	png(output, width=1024, height=768)
    p <- ggplot(data, aes_string(x='factor(generation)', y=y)) +
            theme_bw(base_size=26) +
            geom_boxplot() +
            xlab(xlabel) +
            ylab(ylabel) +
            theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
            theme(axis.title.y = element_text(vjust=1.8)) +
            geom_hline(yintercept=line_data, color='red')
    print(p)
	dev.off()

}

diff_div <- function(x) {
    n <- length(x)
    x <- x[2:n] / x[1:(n-1)]
    return(c(0,x))
}

parse <- function(file, type, legend, limit=NULL, mode='serial', nsim=c(1), diff=FALSE) {
    col.names <- c('tree', 'taxa', 'state', 'time', 'nsim', 'mode')
    data <- read.table(file, row.names=NULL, col.names=col.names)
    # filter by mode (parallel/serial)
    if (!is.null(mode)) {
        data <- data[data$mode==mode,]
    }
    # filter by number of simulations (useful for simmap)
    if (!is.null(nsim)) {
        data <- data[data$nsim==nsim,]
    }
    # projection by execution time and the parameter state/taxa/trees/...
    data <- data[,c('time', type)]
    # add legend
    data$legend <- legend
    # remove rows, if necessary
    if (!is.null(limit)) {
        data <- head(data, limit)
    }
    if (diff==TRUE) {
        data$time <- c(0,diff(data$time))
    }
    # give names to resulting data.frame
    colnames(data) <- c('time', 'value', 'legend')
    return(data)
}
